repos:
  # Autoformat: markdown, javacsript
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier

  # Lint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.40.0
    hooks:
      - id: eslint
        additional_dependencies:
          - "eslint@^8.40.0"
          - "eslint-plugin-nova@^1.7.0"
