repos:
  # Autoformat: markdown, javacsript
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier

  # Lint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.21.0
    hooks:
      - id: eslint
